import Head from 'next/head';
import AboutUs from '../components/AboutUs/AboutUs';
import Blog from '../components/Blog/Blog';
import Contact from '../components/Contact/Contact';
import Footer from '../components/Footer/Footer';
import Hero from '../components/Hero/Hero';
import Navbar from '../components/Navbar/Navbar';
import Services from '../components/Services/Services';
import Status from '../components/Status/Status';
import Team from '../components/Team/Team';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <main className="px-3 lg:px-14 ">
        <Services />
        <AboutUs />
        <Status />
        <Team />
        <Contact />
        <Blog />
        <Footer />
      </main>
    </>
  );
}
